#!/bin/bash
FILES_COUNT=$(find . -iname "*.jpg" -type f | wc -l);
SECONDS=0;
#sec2dhms() { declare -i SS="$1" D=$(( SS / 86400 )) H=$(( SS % 86400 / 3600 )) M=$(( SS % 3600 / 60 )) S=$(( SS % 60 )) [ "$D" -gt 0 ] && echo -n "${D}:" [ "$H" -gt 0 ] && printf "%02g:" "$H" printf "%02g:%02g\n" "$M" "$S" };
echo "ПОДГОНКА РАЗМЕРА И ОБРЕЗКА"
echo "---------------------------------------------------"
echo "$(date '+%R:%S') - Всего файлов для обработки: $FILES_COUNT"
echo "$(date '+%R:%S') - Идет обработка фото..."
find . -iname "*.jpg" -type f -print0 \
| xargs -0 -I{} convert '{}' -gravity center -resize $1 -crop $1x$1+0+0 +repage {};
#find . -iname "*.jpg" -type f -print \
#| xargs -I{} convert '{}' -gravity center -crop $1x$1+0+0 +repage {};
echo "$(date '+%R:%S') - Готово!";
echo "---------------------------------------------------"
echo "Обработка всех фото заняла $(($SECONDS / 3600)) ч. $((($SECONDS / 60) - ($SECONDS / 3600)*60)) мин. $(($SECONDS % 60)) сек.";
echo "Среднее время обработки одного фото: $(bc <<<"scale=2;$SECONDS/$FILES_COUNT") сек.";
